// Generated by Dartloom. This file is overwritten by project upgrade.
import 'package:dartloom_runtime/dartloom_runtime.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:dartloom_settings/dartloom_settings.dart';
import 'package:dartloom_storage/dartloom_storage.dart';
import 'package:dartloom_logging/dartloom_logging.dart';

import 'dart:io';

import 'package:dartloom_autostart/dartloom_autostart.dart';
import 'package:dartloom_localization/dartloom_localization.dart';
import 'package:pengion/l10n/app_localizations.dart';
import 'package:dartloom_resident/dartloom_resident.dart';
import 'package:dartloom_settings_shared_preferences/dartloom_settings_shared_preferences.dart';
import 'package:dartloom_settings_secure_storage/dartloom_settings_secure_storage.dart';
import 'package:dartloom_logging_logger/dartloom_logging_logger.dart';
import 'package:dartloom_autostart_launch_at_startup/dartloom_autostart_launch_at_startup.dart';
import 'package:dartloom_localization_gen_l10n/dartloom_localization_gen_l10n.dart';
import 'package:dartloom_resident_tray/dartloom_resident_tray.dart';

Future<void> initializeDartloom({
  Map<String, DartloomFactory> customFactories = const {},
  DartloomStartupScope scope = DartloomStartupScope.foreground,
}) async {
  late final Map<String, DartloomFactory> factories;
  final officialFactories = <String, DartloomFactory>{
    'shared_preferences': (_) =>
        DartloomBinding<SettingsStore>(SharedPreferencesSettingsStore()),
    'secure_storage': (_) =>
        const DartloomBinding<SettingsStore>(SecureSettingsStore()),
    'logger': (_) => DartloomBinding<AppLogger>(LoggerAppLogger()),
    'launch_at_startup': (context) => DartloomBinding<AutostartService>(
      LaunchAtStartupService(
        appName: context.options['app_name'] as String? ?? "pengion",
        appPath:
            context.options['app_path'] as String? ??
            Platform.resolvedExecutable,
        packageName:
            context.options['package_name'] as String? ?? "com.example.pengion",
      ),
    ),
    'gen_l10n': (_) => DartloomBinding<LocalizationService>(
      GenL10nLocalizationService(
        supportedLocales: AppLocalizations.supportedLocales,
        applicationDelegate: AppLocalizations.delegate,
      ),
    ),
    'tray': (context) async {
      final value = TrayResidentService(
        tooltip:
            context.options['tooltip'] as String? ?? 'Dartloom application',
        linuxIconPath: context.options['icon_path_linux'] as String?,
        macosIconPath: context.options['icon_path_macos'] as String?,
        windowsIconPath: context.options['icon_path_windows'] as String?,
      );
      await value.initialize(
        iconPath: context.options['icon_path'] as String,
        configuration: _dartloomResidentConfiguration(context.options),
      );
      return DartloomBinding<ResidentService>(value, dispose: value.dispose);
    },
  };
  final collisions = officialFactories.keys.toSet().intersection(
    customFactories.keys.toSet(),
  );
  if (collisions.isNotEmpty) {
    throw DartloomException(
      'custom factories cannot replace official factories: $collisions',
    );
  }
  factories = {...officialFactories, ...customFactories};
  await Dartloom.initialize(
    <DartloomRegistration<Object>>[
      if (_dartloomSupportsCurrentPlatform(const {
        "android",
        "ios",
        "windows",
        "macos",
        "linux",
        "web",
      }))
        DartloomRegistration<SettingsStore>(
          capability: 'settings',
          name: "default",
          factory: "shared_preferences",
          scope: DartloomStartupScope.both,
          options: <String, Object?>{},
        ),
      if (_dartloomSupportsCurrentPlatform(const {
        "android",
        "ios",
        "windows",
        "macos",
        "linux",
        "web",
      }))
        DartloomRegistration<SettingsStore>(
          capability: 'settings',
          name: "sync_secrets",
          factory: "secure_storage",
          scope: DartloomStartupScope.both,
          options: <String, Object?>{},
        ),
      if (_dartloomSupportsCurrentPlatform(const {
        "android",
        "ios",
        "windows",
        "macos",
        "linux",
        "web",
      }))
        DartloomRegistration<ReplicaStore>(
          capability: 'storage',
          name: "json",
          factory: "createJsonReplicaStore",
          scope: DartloomStartupScope.both,
          options: <String, Object?>{},
        ),
      if (_dartloomSupportsCurrentPlatform(const {
        "android",
        "ios",
        "windows",
        "macos",
        "linux",
        "web",
      }))
        DartloomRegistration<AppLogger>(
          capability: 'logging',
          name: "default",
          factory: "logger",
          scope: DartloomStartupScope.foreground,
          options: <String, Object?>{},
        ),
      if (_dartloomSupportsCurrentPlatform(const {"windows", "macos", "linux"}))
        DartloomRegistration<AutostartService>(
          capability: 'autostart',
          name: "default",
          factory: "launch_at_startup",
          scope: DartloomStartupScope.foreground,
          options: <String, Object?>{},
        ),
      if (_dartloomSupportsCurrentPlatform(const {
        "android",
        "ios",
        "windows",
        "macos",
        "linux",
        "web",
      }))
        DartloomRegistration<LocalizationService>(
          capability: 'localization',
          name: "default",
          factory: "gen_l10n",
          scope: DartloomStartupScope.foreground,
          options: <String, Object?>{},
        ),
      if (_dartloomSupportsCurrentPlatform(const {"windows", "macos", "linux"}))
        DartloomRegistration<ResidentService>(
          capability: 'resident',
          name: "default",
          factory: "tray",
          scope: DartloomStartupScope.foreground,
          options: <String, Object?>{
            "icon_path": "app_icon.ico",
            "tooltip": "Dartloom application",
          },
        ),
    ],
    factories: factories,
    scope: scope,
  );
}

Future<void> disposeDartloom() => Dartloom.dispose();

String get _dartloomCurrentPlatform => kIsWeb
    ? 'web'
    : switch (defaultTargetPlatform) {
        TargetPlatform.android => 'android',
        TargetPlatform.iOS => 'ios',
        TargetPlatform.linux => 'linux',
        TargetPlatform.macOS => 'macos',
        TargetPlatform.windows => 'windows',
        TargetPlatform.fuchsia => 'fuchsia',
      };

bool _dartloomSupportsCurrentPlatform(Set<String> platforms) {
  return platforms.contains(_dartloomCurrentPlatform);
}

ResidentConfiguration _dartloomResidentConfiguration(
  Map<String, Object?> options,
) {
  final rawMenu = options['menu'];
  final menu = rawMenu is List
      ? rawMenu
            .map((entry) {
              if (entry is! Map) {
                throw DartloomException('resident menu entries must be maps.');
              }
              if (entry['separator'] == true) {
                return const ResidentMenuItem.separator();
              }
              final id = entry['id'];
              final label = entry['label'];
              if (id is! String || label is! String) {
                throw DartloomException(
                  'resident menu items require string id and label.',
                );
              }
              return ResidentMenuItem.action(
                id: id,
                label: label,
                enabled: entry['enabled'] != false,
              );
            })
            .toList(growable: false)
      : const <ResidentMenuItem>[];
  return ResidentConfiguration(
    menu: menu,
    leftClick: _dartloomResidentClickAction(options['left_click']),
    rightClick: _dartloomResidentClickAction(
      options['right_click'],
      fallback: ResidentClickAction.showMenu,
    ),
    exitMenuItemId: options['exit_menu_item_id'] as String? ?? 'quit',
  );
}

ResidentClickAction _dartloomResidentClickAction(
  Object? value, {
  ResidentClickAction fallback = ResidentClickAction.restore,
}) => switch (value) {
  'menu' => ResidentClickAction.showMenu,
  'ignore' => ResidentClickAction.ignore,
  'restore' => ResidentClickAction.restore,
  _ => fallback,
};

final _dartloomFallbackLocalization = GenL10nLocalizationService(
  supportedLocales: AppLocalizations.supportedLocales,
  applicationDelegate: AppLocalizations.delegate,
);
List<Locale> get dartloomSupportedLocales =>
    Dartloom.contains<LocalizationService>()
    ? Dartloom.get<LocalizationService>().supportedLocales
    : _dartloomFallbackLocalization.supportedLocales;
List<LocalizationsDelegate<dynamic>> get dartloomLocalizationsDelegates =>
    Dartloom.contains<LocalizationService>()
    ? Dartloom.get<LocalizationService>().localizationsDelegates
    : _dartloomFallbackLocalization.localizationsDelegates;
